### ISSUE TITLE
invalid (expired) security certificate: repo.vapor.codes/apt/keyring.gpg

### ISSUE THREAD

**Issue by marc-medley** [vapor/apt#26]
The following instructions from https://github.com/vapor/apt  

``` bash
wget -q https://repo.vapor.codes/apt/keyring.gpg -O- | sudo apt-key add -
# gpg: no valid OpenPGP data found.
```

![ExpiredSecurityCertificate](https://user-images.githubusercontent.com/15098151/56868190-06bb4500-69a4-11e9-8d97-9cf7adc09b8d.png)

**Comment by joscdk** [comment]
This is fixed now.

**Comment by Behinder** [comment]
Again, this is not working

**Comment by joscdk** [comment]
@Behinder it should be working now.

We are currently in the process of figuring out what should happen with the APT repo.

**Comment by erdemozgur** [comment]
i am getting the same error now, it says  certificate is expired yesterday. How can i solve this problem?

**Comment by MomoNjf** [comment]
Now I have the problem 😞 
@joscdk

**Comment by joscdk** [comment]
@MomoNjf the APT repo have been deprecated, and we recommend installing Swift from https://www.swift.org

**Comment by Behinder** [comment]
Not very convenient because it merges vapor updates with swift updates,
whenever vapor will be updated shall we update whole swift?

**Comment by 0xTim** [comment]
@Behinder the APT repo only installed the toolbox. You can update if you need it, but chances are you just don't need to install it anyway. 

As for updating the Vapor framework - that's up to you when you do it, and chances are you'll update Swift more than updating major versions of the framework.

**Comment by mitsh** [comment]
it doesn't work again

**Comment by joscdk** [comment]
@mitsh the APT have unfortunately been deprecated, you can download Swift from https://swift.org

**Comment by mitsh** [comment]
hey @joscdk thanks for the fast reply!
